name: Tasks

on: push

jobs:
  lint-php:
    name: "php: ${{ matrix.php }} TYPO3: ${{ matrix.typo3 }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.2', '8.3', '8.4' ]
        typo3: [ '11', '12', '13' ]
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
#      - uses: mirromutth/mysql-action@v1.1
#        with:
#          mysql version: '5.7'
#          mysql database: 'typo3_test'
#          mysql root password: 'root'
      - uses: actions/checkout@v2
      - run: rm composer.lock
      - run: composer require typo3/cms-core="^${{ matrix.typo3 }}" --dev --ignore-platform-req=php+
      - run: composer install --no-interaction --no-progress --ignore-platform-req=php+
      - run: ./vendor/bin/grumphp run --ansi
      #- run: composer test
      #- run: jq 'del(.logs.html)' infection.json > infection.json.new && mv infection.json.new infection.json
      #- run: composer infection
      #- uses: codecov/codecov-action@v3
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }}
      #    file: Resources/Public/test-result/clover.xml
